[package]
name = "pyimports"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
maplit = "1.0.2"
pathfinding = "4.3.3"
rayon = "1.8.0"
rustpython-parser = "0.3.0"
thiserror = "1.0.50"
