version: "3"

tasks:
  test:
    cmds:
      - cargo test --all-features

  bench:
    cmds:
      - cargo bench --all-features

  check.clippy:
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings

  fix.clippy:
    cmds:
      - cargo clippy --all-targets --all-features --fix --allow-staged

  check.fmt:
    cmds:
      - cargo fmt --check

  fix.fmt:
    cmds:
      - cargo fmt

  check:
    cmds:
      - task: test
      - task: check.clippy
      - task: check.fmt

  publish:
    requires:
      vars:
        - name: MODE
          enum: [patch, minor, major]
    cmds:
      - task: check
      - task: check.uncommitted-changes
      - cargo bump {{.MODE}}
      - cargo publish --all-features --dry-run --allow-dirty
      - git add --all
      - git commit -m "Bump version v$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')"
      - git tag "v$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')"
      - cargo publish --all-features
      - git push
      - git push --tags

  check.uncommitted-changes:
    internal: true
    cmds:
      - "[[ -z $(git status -s) ]]"
