version: '3'

tasks:
  test:
    cmds:
      - cargo test

  clippy.check:
    cmds:
      - cargo clippy --all-targets -- -D warnings

  clippy.fix:
    cmds:
      - cargo clippy --fix --allow-staged

  fmt.check:
    cmds:
      - cargo fmt --check

  fmt.fix:
    cmds:
      - cargo fmt

  check:
    cmds:
      - task: test
      - task: clippy.check
      - task: fmt.check
